<?xml version="1.0"?>
<package format="3">
  <name>poli_maze</name>
  <version>0.0.1</version>
  <description>Maze exploration (visit +10), grab at goal, and return to start</description>
  <maintainer email="teampolly33@gmail.com">polly</maintainer>
  <license>MIT</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
